FROM ocaml/opam:alpine-3.6_ocaml-4.04.2 as builder

WORKDIR /core-network
ADD core-network.export core-network.export

RUN sudo apk update && sudo apk add alpine-sdk bash gmp-dev perl autoconf linux-headers &&\
    #opam remote add git https://github.com/ocaml/opam-repository.git &&\
    opam pin add -n mirage-net-psock.0.1.0 https://github.com/sevenEng/mirage-net-psock.git &&\
    opam switch import core-network.export

ADD . .
RUN sudo chown opam: -R . && opam config exec -- jbuilder build bin/relay.exe


FROM alpine:3.6

WORKDIR /core-network
RUN apk update && apk add bash gmp-dev iptables iproute2 tcpdump
COPY --from=builder /core-network/_build/default/bin/relay.exe bcast-relay

LABEL databox.type="core-network-broadcast-relay"

ENTRYPOINT ["./bcast-relay"]