FROM jptmoore/alpine-baseimage-aarch64

USER databox
RUN sudo apk add libffi-dev libressl-dev linux-headers bash autoconf
RUN opam remove ezirmin irmin re.1.7.1 bos lwt
RUN opam pin add -n mirage-net-psock.0.1.0 https://github.com/sevenEng/mirage-net-psock.git

ADD core-network.export core-network.export
RUN opam switch import core-network.export

# add the code
ADD bin bin
RUN sudo chown -R databox:nogroup bin
ADD lib lib
RUN sudo chown -R databox:nogroup lib

# add the build script
ADD build.sh .

# setup ocaml
RUN sudo chmod +x build.sh && sync \
&& ./build.sh \
&& rm -rf /home/databox/bin \
&& rm -rf /home/databox/lib \  
&& rm -rf /home/databox/.opam \
&& rm -rf /home/databox/opam-repository \
&& sudo apk del .build-deps

FROM resin/aarch64-alpine:3.5

USER root
WORKDIR /home/databox/
ADD start.sh start.sh
COPY --from=0 /home/databox/ .
# runtime dependencies
RUN apk update && apk upgrade \
&& apk add libsodium bash gmp-dev iptables iproute2 tcpdump

EXPOSE 8080

LABEL databox.type="export-network"

ENTRYPOINT ["./start.sh"]
